import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

// Load Environment Variables safely
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware
  app.use(express.json({ limit: '10mb' }));

  // Helper to lazily initialize GoogleGenAI with a telemetry User-Agent
  let googleAIClient: GoogleGenAI | null = null;
  function getGeminiClient(): GoogleGenAI {
    if (!googleAIClient) {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        throw new Error("GEMINI_API_KEY is not configured in environment secrets.");
      }
      googleAIClient = new GoogleGenAI({
        apiKey,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          }
        }
      });
    }
    return googleAIClient;
  }

  // API Endpoint: Health Check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", time: new Date().toISOString() });
  });

  // API Endpoint: Custom VBA Macro Generator using Gemini 3.5 Flash
  app.post("/api/gemini/generate-macro", async (req, res) => {
    try {
      const { description, businessType, sheetStructure } = req.body;

      if (!description) {
        return res.status(400).json({ error: "Missing macro description query in request body." });
      }

      const client = getGeminiClient();

      const systemPrompt = `You are "Dremo Analyst Pro", a senior Excel VBA developer and retail POS systems consultant. 
Your goal is to write a highly optimized, clean, safe, and fully working VBA Excel Macro script tailored to the user's POS business request, avoiding any truncated code.
Always use explicit variable declarations (Option Explicit in VBA), include inline explanation comments, and structure variables elegantly. Do not write generic drafts. Make the code solid and robust (such as checking if sheets exist, handling errors nicely).`;

      const userPrompt = `Generate a VBA macro for a sheet of type '${businessType || "Retail POS"}'.
Request Details: ${description}
Spreadsheet Column Structure: ${sheetStructure || "Standard logging schema"}

Please provide a structured JSON response containing:
1. "title": A descriptive, catchy title for this custom macro.
2. "vbaCode": The full copy-pasteable formatted VBA Macro code, starting with code declarations and ending with End Sub or End Function.
3. "explanation": A detailed, markdown-formatted guide detailing what the script does, variable configurations, and specific Excel instructions on how to link/trigger this script.`;

      const aiResponse = await client.models.generateContent({
        model: "gemini-3.5-flash",
        contents: userPrompt,
        config: {
          systemInstruction: systemPrompt,
          temperature: 0.2, // Low temperature for high precision coding
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              title: {
                type: Type.STRING,
                description: "Name of the custom macro script"
              },
              vbaCode: {
                type: Type.STRING,
                description: "Complete Excel VBA script, including comments"
              },
              explanation: {
                type: Type.STRING,
                description: "Step-by-step setup guides, buttons, warning thresholds, in clean Markdown format"
              }
            },
            required: ["title", "vbaCode", "explanation"]
          }
        }
      });

      const responseText = aiResponse.text;
      if (!responseText) {
        return res.status(500).json({ error: "No response was generated by the AI model." });
      }

      // Parse JSON from Gemini response
      const parsedData = JSON.parse(responseText.trim());
      res.json(parsedData);

    } catch (innerError: any) {
      console.error("VBA Generation Error Details:", innerError);
      res.status(500).json({ 
        error: innerError.message || "An error occurred during Gemini macro code generation.",
        details: "Ensure process.env.GEMINI_API_KEY is set in settings panel."
      });
    }
  });

  // Integrating Vite in Dev mode, or static file server in Production
  if (process.env.NODE_ENV !== "production") {
    console.log("Starting server in DEVELOPMENT mode with Vite Middleware...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Starting server in PRODUCTION mode with static file delivery...");
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Dremo Server is running and listening on http://0.0.0.0:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error("Critical Server Startup Failure:", err);
});
